import { createApi } from "@reduxjs/toolkit/query/react";
import customBaseQuery from "../queryBuilder/customQuery";

const apiSlice = createApi({
  reducerPath: "api",
  baseQuery: customBaseQuery,
  tagTypes: [
    "User",
    "Employee",
    "Leave",
    "SalaryBand",
    "Shifts",
    "Rota",
    "Expenses",
    "ExpenseCategories",
    "ExpenseSummary",
    "IncomeCategories",
    "Income",
    "IncomeSummary",
    "PayrollRun",
    "PayrollConfiguration",
    "PayrollPayslip",
    "PayrollRti",
    "PayrollRules",
    "Accounting",
    "AuditLogs",
    "BankAccounts",
    "BankTransactions",
    "Bills",
    "Customers",
    "Invoices",
    "Expenses",
    "Journals",
    "Payments",
    "Periods",
    "Reconciliations",
    "RecurringTemplates",
    "Reports",
    "Suppliers",
    "Vat",
  ],
  endpoints: (builder) => ({}),
  keepUnusedDataFor: 60,
});

export default apiSlice;
